import type { Metadata } from "next";
import { Inter, Poppins } from 'next/font/google';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BubbleMenu from './components/BubbleMenu';
import Image from 'next/image';

const items = [
  {
    label: 'home',
    href: '#home',
    ariaLabel: 'Home',
    rotation: -8,
    hoverStyles: { bgColor: '#3b82f6', textColor: '#ffffff' , }
  },
  {
    label: 'about',
    href: '#about',
    ariaLabel: 'About',
    rotation: 8,
    hoverStyles: { bgColor: '#10b981', textColor: '#ffffff' }
  },
  {
    label: 'projects',
    href: '#projects',
    ariaLabel: 'Projects',
    rotation: 8,
    hoverStyles: { bgColor: '#f59e0b', textColor: '#ffffff' }
  },
   {
    label: 'tech stack',
    href: '#skills',
    ariaLabel: 'tech stack',
    rotation: -8,
    hoverStyles: { bgColor: '#8b5cf6', textColor: '#ffffff' }
  },
  {
    label: 'certif',
    href: '#certif',
    ariaLabel: 'certif',
    rotation: 8,
    hoverStyles: { bgColor: '#ef4444', textColor: '#ffffff' }
  },
  {
    label: 'contact',
    href: '#contact',
    ariaLabel: 'Contact',
    rotation: -8,
    hoverStyles: { bgColor: '#8b5cf6', textColor: '#ffffff' }
  }
];

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
    icons: {
    icon: '/img/Group 2.png', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} antialiased`} >
            

        {/* backdrop optional */}

  {/* Background blur */}
  <div className="absolute inset-0 bg-black/20 " />

  {/* Bubble Menu di tengah */}


      <BubbleMenu
      items={items}
      menuAriaLabel="Navigation"
      menuBg="#ffffff"
      menuContentColor="#111111"
      animationEase="back.out(1.5)"
      animationDuration={0.5}
      staggerDelay={0.12}
    />

          {children}
        
      </body>
    </html>
  );
}
